### PR TITLE
Vedic anusvara support

### PR DESCRIPTION
**Pull request by deepestblue**
This is basic support for the Vedic anusvaras used in RV and KYV (I know very little about SYV, and the anusvara situation in SV seems too complicated for me).

* Added an entry to Ksharanam to represent both the single and double anusvaras.
* Added the single anusvara mapping to Bengali and Kannada, and both mappings to Devanagari and Grantha.

### CODE REVIEW

**Comment by ratreya** [comment]
I am wondering if we should add support for this in all the other transliteration schemes as well. Something like a .gm and .gg. Thoughts?

**Comment by deepestblue** [comment]
Yeah, we absolutely should, but I had no idea what they should be, since I don't use them.

.gm and .gg sound good. Do you know if ITRANS or Baraha have some other mechanism to represent these? I mean, given even the puruṣasūktam has these, these aren't exactly rare ...

**Comment by deepestblue** [comment]
OK pushed out some key-bindings based on my understanding of those keymaps.

**Comment by ratreya** [comment]
Merged - thanks!

**Pull request merged**
